#!/bin/bash

set -eu

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Validating install settings..."

domain=$YNH_APP_ARG_DOMAIN
path_url=$YNH_APP_ARG_PATH
app_port=$(ynh_find_port --port=18088)
image="ghcr.io/atunbey/assemulator:latest"

ynh_script_progression --message="Saving settings..."
ynh_app_setting_set --app=$app --key=domain --value=$domain
ynh_app_setting_set --app=$app --key=path --value=$path_url
ynh_app_setting_set --app=$app --key=port --value=$app_port
ynh_app_setting_set --app=$app --key=image --value=$image

ynh_script_progression --message="Ensuring Docker and Compose are available..."
ynh_exec_warn_less ynh_install_app_dependencies docker.io docker-compose-plugin

ynh_script_progression --message="Preparing app files..."
ynh_app_setting_set --app=$app --key=final_path --value=$final_path
ynh_safe_rm "$final_path"
mkdir -p "$final_path" "$final_path/data" "$final_path/roms" "$final_path/images" "$final_path/bios"

render_compose_file "$app_port" "$image"

ynh_script_progression --message="Configuring reverse proxy..."
ynh_add_nginx_config

ynh_script_progression --message="Starting Assemulator container..."
compose_pull_up

ynh_script_progression --message="Reloading nginx..."
ynh_systemctl --service=nginx --action=reload

ynh_script_progression --message="Installation of $app completed."
