#!/bin/bash

set -eu

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression --message="Removing reverse proxy config..."
ynh_remove_nginx_config

ynh_script_progression --message="Stopping Assemulator container..."
compose_down_if_exists

ynh_script_progression --message="Removing app files..."
ynh_safe_rm "$final_path"

ynh_script_progression --message="Reloading nginx..."
ynh_systemctl --service=nginx --action=reload
