#!/bin/bash

set -eu

source _common.sh
source /usr/share/yunohost/helpers

domain=$(get_setting_or_die domain)
path_url=$(get_setting_or_die path)
app_port=$(get_setting_or_die port)
image=$(get_setting_or_die image)

ynh_script_progression --message="Ensuring Docker and Compose are available..."
ynh_exec_warn_less ynh_install_app_dependencies docker.io docker-compose-plugin

ynh_script_progression --message="Stopping running container before restore..."
compose_down_if_exists

ynh_script_progression --message="Restoring Assemulator files..."
ynh_safe_rm "$final_path"
mkdir -p "$final_path"
ynh_restore_file --origin_path="$final_path"

ynh_script_progression --message="Refreshing compose config from settings..."
render_compose_file "$app_port" "$image"

ynh_script_progression --message="Restoring reverse proxy configuration..."
ynh_add_nginx_config

ynh_script_progression --message="Restarting container..."
compose_pull_up

ynh_script_progression --message="Reloading nginx..."
ynh_systemctl --service=nginx --action=reload
